# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ga25qic/Schreibtisch/Dissertation/codes/swe-benchmark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ga25qic/Schreibtisch/Dissertation/codes/swe-benchmark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ga25qic/Schreibtisch/Dissertation/codes/swe-benchmark/CMakeFiles /home/ga25qic/Schreibtisch/Dissertation/codes/swe-benchmark/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ga25qic/Schreibtisch/Dissertation/codes/swe-benchmark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named swe_benchmark_mpioverdecomp

# Build rule for target.
swe_benchmark_mpioverdecomp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swe_benchmark_mpioverdecomp
.PHONY : swe_benchmark_mpioverdecomp

# fast build rule for target.
swe_benchmark_mpioverdecomp/fast:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/build
.PHONY : swe_benchmark_mpioverdecomp/fast

src/blocks/SWE_DimensionalSplittingMPIOverdecomp.o: src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.o

.PHONY : src/blocks/SWE_DimensionalSplittingMPIOverdecomp.o

# target to build an object file
src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.o:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.o
.PHONY : src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.o

src/blocks/SWE_DimensionalSplittingMPIOverdecomp.i: src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.i

.PHONY : src/blocks/SWE_DimensionalSplittingMPIOverdecomp.i

# target to preprocess a source file
src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.i:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.i
.PHONY : src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.i

src/blocks/SWE_DimensionalSplittingMPIOverdecomp.s: src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.s

.PHONY : src/blocks/SWE_DimensionalSplittingMPIOverdecomp.s

# target to generate assembly for a file
src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.s:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.s
.PHONY : src/blocks/SWE_DimensionalSplittingMPIOverdecomp.cpp.s

src/examples/swe_mpi_overdecomp.o: src/examples/swe_mpi_overdecomp.cpp.o

.PHONY : src/examples/swe_mpi_overdecomp.o

# target to build an object file
src/examples/swe_mpi_overdecomp.cpp.o:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/examples/swe_mpi_overdecomp.cpp.o
.PHONY : src/examples/swe_mpi_overdecomp.cpp.o

src/examples/swe_mpi_overdecomp.i: src/examples/swe_mpi_overdecomp.cpp.i

.PHONY : src/examples/swe_mpi_overdecomp.i

# target to preprocess a source file
src/examples/swe_mpi_overdecomp.cpp.i:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/examples/swe_mpi_overdecomp.cpp.i
.PHONY : src/examples/swe_mpi_overdecomp.cpp.i

src/examples/swe_mpi_overdecomp.s: src/examples/swe_mpi_overdecomp.cpp.s

.PHONY : src/examples/swe_mpi_overdecomp.s

# target to generate assembly for a file
src/examples/swe_mpi_overdecomp.cpp.s:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/examples/swe_mpi_overdecomp.cpp.s
.PHONY : src/examples/swe_mpi_overdecomp.cpp.s

src/writer/NetCdfWriter.o: src/writer/NetCdfWriter.cpp.o

.PHONY : src/writer/NetCdfWriter.o

# target to build an object file
src/writer/NetCdfWriter.cpp.o:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/writer/NetCdfWriter.cpp.o
.PHONY : src/writer/NetCdfWriter.cpp.o

src/writer/NetCdfWriter.i: src/writer/NetCdfWriter.cpp.i

.PHONY : src/writer/NetCdfWriter.i

# target to preprocess a source file
src/writer/NetCdfWriter.cpp.i:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/writer/NetCdfWriter.cpp.i
.PHONY : src/writer/NetCdfWriter.cpp.i

src/writer/NetCdfWriter.s: src/writer/NetCdfWriter.cpp.s

.PHONY : src/writer/NetCdfWriter.s

# target to generate assembly for a file
src/writer/NetCdfWriter.cpp.s:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/writer/NetCdfWriter.cpp.s
.PHONY : src/writer/NetCdfWriter.cpp.s

src/writer/VtkWriter.o: src/writer/VtkWriter.cpp.o

.PHONY : src/writer/VtkWriter.o

# target to build an object file
src/writer/VtkWriter.cpp.o:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/writer/VtkWriter.cpp.o
.PHONY : src/writer/VtkWriter.cpp.o

src/writer/VtkWriter.i: src/writer/VtkWriter.cpp.i

.PHONY : src/writer/VtkWriter.i

# target to preprocess a source file
src/writer/VtkWriter.cpp.i:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/writer/VtkWriter.cpp.i
.PHONY : src/writer/VtkWriter.cpp.i

src/writer/VtkWriter.s: src/writer/VtkWriter.cpp.s

.PHONY : src/writer/VtkWriter.s

# target to generate assembly for a file
src/writer/VtkWriter.cpp.s:
	$(MAKE) -f CMakeFiles/swe_benchmark_mpioverdecomp.dir/build.make CMakeFiles/swe_benchmark_mpioverdecomp.dir/src/writer/VtkWriter.cpp.s
.PHONY : src/writer/VtkWriter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... swe_benchmark_mpioverdecomp"
	@echo "... edit_cache"
	@echo "... src/blocks/SWE_DimensionalSplittingMPIOverdecomp.o"
	@echo "... src/blocks/SWE_DimensionalSplittingMPIOverdecomp.i"
	@echo "... src/blocks/SWE_DimensionalSplittingMPIOverdecomp.s"
	@echo "... src/examples/swe_mpi_overdecomp.o"
	@echo "... src/examples/swe_mpi_overdecomp.i"
	@echo "... src/examples/swe_mpi_overdecomp.s"
	@echo "... src/writer/NetCdfWriter.o"
	@echo "... src/writer/NetCdfWriter.i"
	@echo "... src/writer/NetCdfWriter.s"
	@echo "... src/writer/VtkWriter.o"
	@echo "... src/writer/VtkWriter.i"
	@echo "... src/writer/VtkWriter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

